/*
 * Copyright (c) 2024-2026 valo.media GmbH
 * All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
    throw err;
});

// Ensure environment variables are read.
require('../config/env');

const fs = require('fs');
const chalk = require('chalk');
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const semver = require('semver');
const open = require('open');
const paths = require('../config/paths');
const configFactory = require('../config/webpack.config');
const createDevServerConfig = require('../config/webpackDevServer.config');
const getClientEnvironment = require('../config/env');
const {
    checkRequiredFiles,
    choosePort,
    clearConsole,
    createCompiler,
    prepareProxy,
    prepareUrls,
} = require('./utils');

const env = getClientEnvironment(paths.publicUrlOrPath.slice(0, -1));
const useYarn = fs.existsSync(paths.yarnLockFile);
const isInteractive = process.stdout.isTTY;

// Warn and crash if required files are missing
if (!checkRequiredFiles([paths.appHtml, paths.appIndexJs])) {
    process.exit(1);
}

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

if (process.env.HOST) {
    console.log(
        chalk.cyan(`Attempting to bind to HOST environment variable: ${chalk.yellow(chalk.bold(process.env.HOST))}`)
    );
    console.log(`If this was unintentional, check that you haven't mistakenly set it in your shell.`);
    console.log();
}

const react = require(require.resolve('react', {paths: [paths.appPath]}));
choosePort(HOST, DEFAULT_PORT)
    .then(port => {
        if (port == null) {
            // We have not found a port.
            return;
        }

        const config = configFactory('development');
        const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';
        const appName = require(paths.appPackageJson).name;

        const useTypeScript = fs.existsSync(paths.appTsConfig);
        const urls = prepareUrls(
            protocol,
            HOST,
            port,
            paths.publicUrlOrPath.slice(0, -1)
        );

        // Create a webpack compiler configured with custom messages.
        const compiler = createCompiler({
            appName,
            config,
            urls,
            useYarn,
            useTypeScript,
            webpack,
        });
        const proxyConfig = prepareProxy(
            process.env.TOWER_PROXY_TARGET,
            paths.appPublic,
            paths.publicUrlOrPath
        );
        // Serve webpack assets generated by the compiler over a web server.
        const serverConfig = {
            ...createDevServerConfig(proxyConfig, urls.lanUrlForConfig),
            host: HOST,
            port,
        };
        const devServer = new WebpackDevServer(serverConfig, compiler);

        // Launch WebpackDevServer.
        // noinspection JSUnresolvedReference
        devServer.startCallback(() => {
            if (isInteractive) {
                clearConsole();
            }

            if (env.raw.FAST_REFRESH && semver.lt(react.version, '16.10.0')) {
                console.log(
                    chalk.yellow(
                        `Fast Refresh requires React 16.10 or higher. You are using React ${react.version}.`
                    )
                );
            }

            console.log(chalk.cyan('Starting the development server...\n'));
            open(urls.localUrlForBrowser);
        });

        ['SIGINT', 'SIGTERM'].forEach(function (sig) {
            process.on(sig, function () {
                devServer.stop();
                process.exit();
            });
        });

        if (process.env.CI !== 'true') {
            // Gracefully exit when stdin ends
            process.stdin.on('end', function () {
                devServer.stop();
                process.exit();
            });
        }
    })
    .catch(err => {
        if (err && err.message) {
            console.log(err.message);
        }
        process.exit(1);
    });
