name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  node-npm-ci:
    uses: valomedia/github-workflows/.github/workflows/node-npm-ci.yml@3db4e67ced211fbe0092fd9b66e024837e575c65 # v1.2.0
    permissions:
      contents: read
