name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  node-npm-ci:
    uses: valomedia/github-workflows/.github/workflows/node-npm-ci.yml@v1.1.0
    permissions:
      contents: read
